# 球队中英文名称对照表 (竞彩官方译名标准)
TEAM_NAME_CN = {
    # ===== 英超 =====
    'Manchester City': '曼彻斯特城', 'Man City': '曼彻斯特城',
    'Liverpool': '利物浦', 'Liverpool FC': '利物浦',
    'Arsenal': '阿森纳', 'Arsenal FC': '阿森纳',
    'Manchester United': '曼彻斯特联', 'Man United': '曼彻斯特联',
    'Chelsea': '切尔西', 'Chelsea FC': '切尔西',
    'Tottenham Hotspur': '托特纳姆热刺', 'Tottenham': '托特纳姆热刺',
    'Newcastle United': '纽卡斯尔联', 'Newcastle': '纽卡斯尔联',
    'Brighton & Hove Albion': '布赖顿', 'Brighton': '布赖顿',
    'Aston Villa': '阿斯顿维拉', 'West Ham United': '西汉姆联', 'West Ham': '西汉姆联',
    'Crystal Palace': '水晶宫', 'Everton': '埃弗顿', 'Everton FC': '埃弗顿',
    'Wolverhampton Wanderers': '狼队', 'Wolves': '狼队',
    'Fulham': '富勒姆', 'Fulham FC': '富勒姆',
    'Brentford': '布伦特福德', 'Brentford FC': '布伦特福德',
    'Nottingham Forest': '诺丁汉森林',
    'Bournemouth': '伯恩茅斯', 'AFC Bournemouth': '伯恩茅斯',
    'Leicester City': '莱切斯特城', 'Leicester': '莱切斯特城',
    'Southampton': '南安普敦', 'Southampton FC': '南安普敦',
    'Leeds United': '利兹联', 'Leeds': '利兹联',
    'Burnley': '伯恩利', 'Burnley FC': '伯恩利',
    'Sheffield United': '谢菲尔德联', 'Sheffield Utd': '谢菲尔德联',
    'Luton Town': '卢顿',
    'Ipswich Town': '伊普斯维奇',

    # ===== 西甲 =====
    'Real Madrid': '皇家马德里', 'Real Madrid CF': '皇家马德里',
    'Barcelona': '巴塞罗那', 'FC Barcelona': '巴塞罗那',
    'Atletico Madrid': '马德里竞技', 'Atlético Madrid': '马德里竞技',
    'Real Sociedad': '皇家社会',
    'Athletic Bilbao': '毕尔巴鄂竞技', 'Athletic Club': '毕尔巴鄂竞技',
    'Real Betis': '皇家贝蒂斯', 'Real Betis Balompié': '皇家贝蒂斯',
    'Villarreal': '比利亚雷亚尔', 'Villarreal CF': '比利亚雷亚尔',
    'Sevilla': '塞维利亚', 'Sevilla FC': '塞维利亚',
    'Valencia': '巴伦西亚', 'Valencia CF': '巴伦西亚',
    'Osasuna': '奥萨苏纳', 'CA Osasuna': '奥萨苏纳',
    'Girona': '赫罗纳', 'Girona FC': '赫罗纳',
    'Getafe': '赫塔费', 'Getafe CF': '赫塔费',
    'Celta Vigo': '维戈塞尔塔', 'RC Celta': '维戈塞尔塔',
    'Rayo Vallecano': '巴列卡诺',
    'Mallorca': '马洛卡', 'RCD Mallorca': '马洛卡',
    'Alaves': '阿拉维斯', 'Deportivo Alavés': '阿拉维斯',
    'Las Palmas': '拉斯帕尔马斯', 'UD Las Palmas': '拉斯帕尔马斯',
    'Espanyol': '西班牙人', 'RCD Espanyol': '西班牙人',
    'Real Valladolid': '巴利亚多利德',
    'Leganes': '莱加内斯', 'CD Leganés': '莱加内斯',
    'Cadiz': '加的斯', 'Cádiz CF': '加的斯',
    'Granada': '格拉纳达', 'Granada CF': '格拉纳达',
    'Elche': '埃尔切', 'Elche CF': '埃尔切',
    'Almeria': '阿尔梅里亚', 'UD Almería': '阿尔梅里亚',

    # ===== 德甲 =====
    'Bayern Munich': '拜仁慕尼黑', 'FC Bayern München': '拜仁慕尼黑',
    'Borussia Dortmund': '多特蒙德', 'BVB': '多特蒙德',
    'RB Leipzig': '莱比锡红牛', 'RasenBallsport Leipzig': '莱比锡红牛',
    'Bayer Leverkusen': '勒沃库森', 'Bayer 04 Leverkusen': '勒沃库森',
    'Eintracht Frankfurt': '法兰克福',
    'SC Freiburg': '弗赖堡', 'Freiburg': '弗赖堡',
    'VfL Wolfsburg': '沃尔夫斯堡', 'Wolfsburg': '沃尔夫斯堡',
    'Borussia Mönchengladbach': '门兴格拉德巴赫', 'Borussia M.Gladbach': '门兴格拉德巴赫', 'Mönchengladbach': '门兴格拉德巴赫',
    'VfB Stuttgart': '斯图加特', 'Stuttgart': '斯图加特',
    'TSG Hoffenheim': '霍芬海姆', 'Hoffenheim': '霍芬海姆',
    '1. FC Union Berlin': '柏林联合', 'Union Berlin': '柏林联合',
    'FC Augsburg': '奥格斯堡', 'Augsburg': '奥格斯堡',
    'Werder Bremen': '云达不来梅', 'SV Werder Bremen': '云达不来梅',
    '1. FC Heidenheim': '海登海姆', 'Heidenheim': '海登海姆',
    'FSV Mainz 05': '美因茨', 'Mainz 05': '美因茨', 'Mainz': '美因茨',
    'VfL Bochum': '波鸿', 'Bochum': '波鸿',
    'FC Köln': '科隆', '1. FC Köln': '科隆', 'Cologne': '科隆',
    'Darmstadt 98': '达姆施塔特', 'SV Darmstadt 98': '达姆施塔特',
    'Hertha BSC': '柏林赫塔', 'Hertha Berlin': '柏林赫塔',
    'Schalke 04': '沙尔克04', 'FC Schalke 04': '沙尔克04',
    'Hamburger SV': '汉堡',

    # ===== 意甲 =====
    'Inter Milan': '国际米兰', 'FC Internazionale': '国际米兰', 'Internazionale': '国际米兰',
    'AC Milan': 'AC米兰', 'Milan': 'AC米兰',
    'Juventus': '尤文图斯', 'Juventus FC': '尤文图斯',
    'Napoli': '那不勒斯', 'SSC Napoli': '那不勒斯',
    'Lazio': '拉齐奥', 'SS Lazio': '拉齐奥',
    'Roma': '罗马', 'AS Roma': '罗马',
    'Atalanta': '亚特兰大', 'Atalanta BC': '亚特兰大',
    'Fiorentina': '佛罗伦萨', 'ACF Fiorentina': '佛罗伦萨',
    'Bologna': '博洛尼亚', 'Bologna FC': '博洛尼亚',
    'Torino': '都灵', 'Torino FC': '都灵',
    'Genoa': '热那亚', 'Genoa CFC': '热那亚',
    'Monza': '蒙扎', 'AC Monza': '蒙扎',
    'Udinese': '乌迪内斯', 'Udinese Calcio': '乌迪内斯',
    'Lecce': '莱切', 'US Lecce': '莱切',
    'Empoli': '恩波利', 'Empoli FC': '恩波利',
    'Cagliari': '卡利亚里', 'Cagliari Calcio': '卡利亚里',
    'Verona': '维罗纳', 'Hellas Verona': '维罗纳',
    'Parma': '帕尔马', 'Parma Calcio 1913': '帕尔马',
    'Como': '科莫', 'Como 1907': '科莫',
    'Venezia': '威尼斯', 'Venezia FC': '威尼斯',
    'Salernitana': '萨勒尼塔纳',
    'Sassuolo': '萨索洛', 'US Sassuolo': '萨索洛',
    'Spezia': '斯佩齐亚',
    'Cremonese': '克雷莫纳',
    'Sampdoria': '桑普多利亚', 'UC Sampdoria': '桑普多利亚',

    # ===== 法甲 =====
    'Paris Saint-Germain': '巴黎圣日尔曼', 'PSG': '巴黎圣日尔曼',
    'Monaco': '摩纳哥', 'AS Monaco': '摩纳哥',
    'Marseille': '马赛', 'Olympique Marseille': '马赛',
    'Lyon': '里昂', 'Olympique Lyonnais': '里昂',
    'Nice': '尼斯', 'OGC Nice': '尼斯',
    'Lille': '里尔', 'LOSC Lille': '里尔',
    'Rennes': '雷恩', 'Stade Rennais': '雷恩', 'Stade Rennais FC': '雷恩',
    'Lens': '朗斯', 'RC Lens': '朗斯',
    'Strasbourg': '斯特拉斯堡', 'RC Strasbourg': '斯特拉斯堡',
    'Montpellier': '蒙彼利埃', 'Montpellier HSC': '蒙彼利埃',
    'Reims': '兰斯', 'Stade de Reims': '兰斯',
    'Toulouse': '图卢兹', 'Toulouse FC': '图卢兹',
    'Brest': '布雷斯特', 'Stade Brestois': '布雷斯特',
    'Nantes': '南特', 'FC Nantes': '南特',
    'Auxerre': '欧塞尔', 'AJ Auxerre': '欧塞尔',
    'Le Havre': '勒阿弗尔', 'Le Havre AC': '勒阿弗尔',
    'Clermont Foot': '克莱蒙',
    'Lorient': '洛里昂', 'FC Lorient': '洛里昂',
    'Angers': '昂热', 'Angers SCO': '昂热',
    'Metz': '梅斯', 'FC Metz': '梅斯',
    'Saint-Etienne': '圣埃蒂安', 'AS Saint-Étienne': '圣埃蒂安',
    'Bordeaux': '波尔多', 'Girondins Bordeaux': '波尔多',
    'Troyes': '特鲁瓦',

    # ===== 中超 =====
    'Shanghai Port': '上海海港', 'Shanghai SIPG': '上海海港',
    'Shandong Taishan': '山东泰山', 'Shandong Luneng': '山东泰山',
    'Beijing Guoan': '北京国安',
    'Chengdu Rongcheng': '成都蓉城',
    'Shanghai Shenhua': '上海申花',
    'Wuhan Three Towns': '武汉三镇',
    'Zhejiang Professional': '浙江队', 'Zhejiang': '浙江队',
    'Tianjin Jinmen Tiger': '天津津门虎', 'Tianjin Jinmen Tiger FC': '天津津门虎',
    'Henan Songshan Longmen': '河南队', 'Henan': '河南队', 'Henan FC': '河南队',
    'Changchun Yatai': '长春亚泰',
    'Qingdao West Coast': '青岛西海岸',
    'Qingdao Hainiu': '青岛海牛',
    'Meizhou Hakka': '梅州客家',
    'Cangzhou Mighty Lions': '沧州雄狮',
    'Shenzhen Peng City': '深圳新鹏城',
    'Nantong Zhiyun': '南通支云',
    'Dalian Professional': '大连人', 'Dalian Pro': '大连人',
    'Shenzhen FC': '深圳队',
    'Guangzhou FC': '广州队', 'Guangzhou': '广州队',
    'Liaoning Tieren FC': '辽宁铁人',
    'Chongqing Tonglianglong FC': '重庆铜梁龙',

    # ===== 日职 =====
    'Yokohama F. Marinos': '横滨水手', 'Yokohama F·Marinos': '横滨水手',
    'Kawasaki Frontale': '川崎前锋',
    'Urawa Red Diamonds': '浦和红钻', 'Urawa Reds': '浦和红钻',
    'Kashima Antlers': '鹿岛鹿角',
    'Gamba Osaka': '大阪钢巴',
    'Nagoya Grampus': '名古屋鲸八',
    'Sanfrecce Hiroshima': '广岛三箭',
    'FC Tokyo': '东京FC',
    'Kashiwa Reysol': '柏太阳神',
    'Albirex Niigata': '新泻天鹅', 'Albirex Niigata FC': '新泻天鹅',
    'Cerezo Osaka': '大阪樱花',
    'Avispa Fukuoka': '福冈黄蜂',
    'Vissel Kobe': '神户胜利船',
    'Sagan Tosu': '鸟栖沙岩',
    'Shonan Bellmare': '湘南海洋',
    'Kyoto Sanga': '京都不死鸟', 'Kyoto Sanga FC': '京都不死鸟',
    'Hokkaido Consadole Sapporo': '札幌冈萨多', 'Consadole Sapporo': '札幌冈萨多',
    'Jubilo Iwata': '磐田喜悦',
    'Tokyo Verdy': '东京绿茵',
    'Shimizu S-Pulse': '清水鼓动',
    'Vegalta Sendai': '仙台七夕',
    'Oita Trinita': '大分三神',
    'Matsumoto Yamaga': '松本山雅',

    # ===== 韩K联 =====
    'Ulsan HD': '蔚山现代', 'Ulsan Hyundai': '蔚山现代', 'Ulsan HD FC': '蔚山现代',
    'Jeonbuk Hyundai Motors': '全北现代', 'Jeonbuk Motors': '全北现代',
    'Pohang Steelers': '浦项制铁',
    'FC Seoul': '首尔FC',
    'Jeju SK': '济州联', 'Jeju United': '济州联',
    'Daegu FC': '大邱FC',
    'Suwon Samsung Bluewings': '水原三星', 'Suwon Bluewings': '水原三星',
    'Incheon United': '仁川联',
    'Gwangju FC': '光州FC',
    'Daejeon Hana Citizen': '大田市民',
    'Gangwon FC': '江原FC',
    'FC Anyang': '安养FC',
    'Suwon FC': '水原FC',
    'Gimcheon Sangmu': '金泉尚武', 'Sangju Sangmu': '金泉尚武',
    'Seongnam FC': '城南FC',

    # ===== 荷甲 =====
    'Ajax': '阿贾克斯', 'AFC Ajax': '阿贾克斯',
    'PSV Eindhoven': '埃因霍温', 'PSV': '埃因霍温',
    'Feyenoord': '费耶诺德', 'Feyenoord Rotterdam': '费耶诺德',
    'AZ Alkmaar': '阿尔克马尔', 'AZ': '阿尔克马尔',
    'FC Twente': '特温特',
    'FC Utrecht': '乌德勒支',
    'Sparta Rotterdam': '鹿特丹斯巴达',
    'SC Heerenveen': '海伦芬', 'Heerenveen': '海伦芬',
    'FC Groningen': '格罗宁根',
    'Vitesse': '维迪斯', 'Vitesse Arnhem': '维迪斯',
    'NEC Nijmegen': '奈梅亨',
    'Go Ahead Eagles': '前进之鹰',
    'PEC Zwolle': '兹沃勒',
    'Fortuna Sittard': '福图纳锡塔德',
    'RKC Waalwijk': '瓦尔韦克',
    'Heracles Almelo': '赫拉克勒斯',
    'Willem II': '威廉二世',
    'FC Volendam': '福伦丹',
    'Excelsior': '精英',
    'Almere City': '阿尔梅勒城', 'Almere City FC': '阿尔梅勒城',
    'NAC Breda': '布雷达',

    # ===== 葡超 =====
    'Benfica': '本菲卡', 'SL Benfica': '本菲卡',
    'FC Porto': '波尔图', 'Porto': '波尔图',
    'Sporting CP': '里斯本竞技', 'Sporting Lisbon': '里斯本竞技',
    'SC Braga': '布拉加', 'Braga': '布拉加',
    'Vitoria Guimaraes': '吉马良斯', 'Vitória SC': '吉马良斯',
    'Boavista': '博阿维斯塔', 'Boavista FC': '博阿维斯塔',
    'Famalicao': '法马利康', 'FC Famalicão': '法马利康',
    'Rio Ave': '里奥阿维', 'Rio Ave FC': '里奥阿维',
    'Gil Vicente': '吉尔维森特', 'Gil Vicente FC': '吉尔维森特',
    'Estoril': '埃斯托里尔', 'GD Estoril Praia': '埃斯托里尔',
    'Casa Pia': '卡萨皮亚', 'Casa Pia AC': '卡萨皮亚',
    'Portimonense': '波尔蒂芒人',
    'Maritimo': '马里迪莫', 'CS Marítimo': '马里迪莫',
    'Pacos de Ferreira': '费雷拉', 'FC Paços de Ferreira': '费雷拉',
    'Santa Clara': '圣克拉拉', 'CD Santa Clara': '圣克拉拉',
    'Arouca': '阿罗卡', 'FC Arouca': '阿罗卡',
    'Chaves': '沙维什', 'GD Chaves': '沙维什',
    'Moreirense': '摩雷伦斯', 'Moreirense FC': '摩雷伦斯',
    'Vizela': '维泽拉', 'FC Vizela': '维泽拉',
    'Estrela Amadora': '阿马多拉之星', 'CF Estrela': '阿马多拉之星',
    'AVS Futebol SAD': 'AVS',
    'Nacional': '马德拉国民', 'CD Nacional': '马德拉国民',
    'Farense': '法伦斯', 'SC Farense': '法伦斯',

    # ===== 土超 =====
    'Galatasaray': '加拉塔萨雷', 'Galatasaray SK': '加拉塔萨雷',
    'Fenerbahce': '费内巴切', 'Fenerbahçe': '费内巴切',
    'Besiktas': '贝西克塔斯', 'Beşiktaş': '贝西克塔斯',
    'Trabzonspor': '特拉布宗体育',
    'Istanbul Basaksehir': '伊斯坦布尔', 'Başakşehir': '伊斯坦布尔',
    'Adana Demirspor': '阿达纳德米尔体育',
    'Konyaspor': '科尼亚体育',
    'Kayserispor': '开塞利体育',
    'Kasimpasa': '卡森帕萨', 'Kasımpaşa': '卡森帕萨',
    'Antalyaspor': '安塔利亚体育',
    'Sivasspor': '锡瓦斯体育',
    'Alanyaspor': '阿拉尼亚体育',
    'Gaziantep FK': '加济安泰普',
    'Hatayspor': '哈塔伊体育',
    'Samsunspor': '萨姆松体育',
    'Caykur Rizespor': '里泽体育', 'Çaykur Rizespor': '里泽体育',
    'Pendikspor': '彭迪克体育',
    'Fatih Karagumruk': '卡拉古姆鲁克', 'Fatih Karagümrük': '卡拉古姆鲁克',
    'Ankaragucu': '安卡拉古库', 'MKE Ankaragücü': '安卡拉古库',
    'Istanbulspor': '伊斯坦布尔体育',

    # ===== 挪超 =====
    'Bodo/Glimt': '博德闪耀', 'FK Bodø/Glimt': '博德闪耀',
    'Molde': '莫尔德', 'Molde FK': '莫尔德',
    'Rosenborg': '罗森博格', 'Rosenborg BK': '罗森博格',
    'Viking': '维京', 'Viking FK': '维京',
    'Brann': '布兰', 'SK Brann': '布兰',
    'Lillestrom': '利勒斯特罗姆', 'Lillestrøm SK': '利勒斯特罗姆',
    'Odd': '奥德', 'Odds BK': '奥德',
    'Stromsgodset': '斯特罗姆加斯特', 'Strømsgodset IF': '斯特罗姆加斯特',
    'Sarpsborg 08': '萨普斯堡', 'Sarpsborg 08 FF': '萨普斯堡',
    'Tromso': '特罗姆瑟', 'Tromsø IL': '特罗姆瑟',
    'Valerenga': '瓦勒伦加', 'Vålerenga': '瓦勒伦加',
    'Haugesund': '海于格松', 'FK Haugesund': '海于格松',
    'Sandefjord': '桑纳菲尤尔', 'Sandefjord Fotball': '桑纳菲尤尔',
    'HamKam': '汉坎',
    'Kristiansund': '克里斯蒂安松', 'Kristiansund BK': '克里斯蒂安松',
    'KFUM Oslo': 'KFUM奥斯陆', 'KFUM-Kameratene Oslo': 'KFUM奥斯陆',
    'Aalesund': '奥勒松', 'Aalesunds FK': '奥勒松',
    'Fredrikstad': '腓特烈斯塔', 'Fredrikstad FK': '腓特烈斯塔',
    'Bryne': '布莱尼', 'Bryne FK': '布莱尼',

    # ===== 瑞典超 =====
    'Malmo FF': '马尔默', 'Malmö FF': '马尔默',
    'Djurgardens IF': '尤尔加登', 'Djurgården': '尤尔加登',
    'BK Hacken': '赫根', 'BK Häcken': '赫根',
    'IF Elfsborg': '埃尔夫斯堡',
    'AIK': '索尔纳AIK', 'AIK Stockholm': '索尔纳AIK',
    'Hammarby IF': '哈马比',
    'IFK Norrkoping': '北雪平', 'IFK Norrköping': '北雪平',
    'IFK Goteborg': '哥德堡', 'IFK Göteborg': '哥德堡',
    'Kalmar FF': '卡尔马',
    'Mjallby AIF': '米亚尔比',
    'IK Sirius': '天狼星',
    'IFK Varnamo': '韦纳穆', 'IFK Värnamo': '韦纳穆',
    'Halmstads BK': '哈尔姆斯塔德',
    'GAIS': '加尔斯',
    'IF Brommapojkarna': '布鲁马波卡纳',
    'Degerfors IF': '代格福什',
    'Orgryte IS': '厄尔格里特', 'Örgryte IS': '厄尔格里特',
    'Osters IF': '厄斯特什', 'Östers IF': '厄斯特什',
    'Trelleborgs FF': '特雷勒堡',
    'Ostersunds FK': '厄斯特松德', 'Östersunds FK': '厄斯特松德',

    # ===== 丹超 =====
    'FC Copenhagen': '哥本哈根', 'FC København': '哥本哈根',
    'FC Midtjylland': '中日德兰',
    'Brondby IF': '布隆德比', 'Brøndby IF': '布隆德比',
    'FC Nordsjaelland': '北西兰', 'FC Nordsjælland': '北西兰',
    'Aarhus GF': '奥胡斯', 'AGF': '奥胡斯',
    'Silkeborg IF': '锡尔克堡',
    'Viborg FF': '维堡',
    'Randers FC': '兰讷斯',
    'Odense BK': '欧登塞', 'OB': '欧登塞',
    'Aalborg BK': '奥尔堡', 'AaB': '奥尔堡',
    'Vejle BK': '瓦埃勒',
    'Lyngby BK': '林比',
    'AC Horsens': '霍森斯',
    'Sonderjyske': '桑德捷斯基', 'SønderjyskE': '桑德捷斯基',

    # ===== 波甲 (Ekstraklasa) =====
    'Legia Warszawa': '华沙军团', 'Legia Warsaw': '华沙军团',
    'Lech Poznan': '波兹南莱赫', 'Lech Poznań': '波兹南莱赫',
    'Rakow Czestochowa': '琴斯托霍瓦', 'Raków Częstochowa': '琴斯托霍瓦',
    'Pogon Szczecin': '什切青波贡', 'Pogoń Szczecin': '什切青波贡',
    'Slask Wroclaw': '弗罗茨瓦夫', 'Śląsk Wrocław': '弗罗茨瓦夫',
    'GKS Katowice': '卡托维兹',
    'Radomiak Radom': '拉多米亚克',
    'Jagiellonia Bialystok': '比亚韦斯托克', 'Jagiellonia Białystok': '比亚韦斯托克',
    'Piast Gliwice': '皮亚斯特',
    'Widzew Lodz': '罗兹维德泽夫', 'Widzew Łódź': '罗兹维德泽夫',
    'Gornik Zabrze': '扎布热矿工', 'Górnik Zabrze': '扎布热矿工',
    'Cracovia': '克拉科维亚',
    'Korona Kielce': '凯尔采王冠',
    'Zaglebie Lubin': '卢宾扎格列比', 'Zagłębie Lubin': '卢宾扎格列比',
    'Stal Mielec': '梅莱茨钢铁', 'Stal Mielec': '梅莱茨钢铁',
    'Puszcza Niepolomice': '涅波沃米采',
    'Motor Lublin': '卢布林摩托',

    # ===== 芬超 =====
    'HJK Helsinki': '赫尔辛基', 'HJK': '赫尔辛基',
    'KuPS': '库普斯', 'Kuopion Palloseura': '库普斯',
    'SJK': '塞伊奈约基', 'Seinäjoen Jalkapallokerho': '塞伊奈约基',
    'FC Honka': '洪卡',
    'FC Inter Turku': '图尔库国际', 'Inter Turku': '图尔库国际',
    'VPS': '瓦萨', 'Vaasan Palloseura': '瓦萨',
    'AC Oulu': '奥卢',
    'FC Lahti': '拉赫蒂',
    'Ilves': '伊尔韦斯',
    'IFK Mariehamn': '玛丽港',
    'FC Haka': '哈卡',
    'KTP': '科特卡',

    # ===== 罗甲 (Superliga) =====
    'FCSB': '布加勒斯特星', 'Steaua Bucuresti': '布加勒斯特星',
    'CFR Cluj': '克卢日', 'CFR 1907 Cluj': '克卢日',
    'Universitatea Craiova': '克拉约瓦大学',
    'Rapid Bucuresti': '布加勒斯特快速', 'FC Rapid București': '布加勒斯特快速',
    'Sepsi OSK': '舍佩斯', 'Sepsi OSK Sfântu Gheorghe': '舍佩斯',
    'FC Corvinul Hunedoara': '科尔维努尔',
    'Farul Constanta': '康斯坦察灯塔', 'Farul Constanța': '康斯坦察灯塔',
    'FCV Farul Constanta': '康斯坦察灯塔',
    'Petrolul Ploiesti': '普洛耶什蒂石油', 'Petrolul Ploiești': '普洛耶什蒂石油',
    'FC Botosani': '博托沙尼', 'FC Botoșani': '博托沙尼',
    'UTA Arad': '阿拉德',
    'FC Hermannstadt': '赫尔曼施塔特',
    'Otelul Galati': '加拉茨钢铁', 'Oțelul Galați': '加拉茨钢铁',
    'Dinamo Bucuresti': '布加勒斯特迪纳摩', 'Dinamo București': '布加勒斯特迪纳摩',
    'Gloria Buzau': '布泽乌光荣', 'Gloria Buzău': '布泽乌光荣',
    'Unirea Slobozia': '斯洛博齐亚',

    # ===== 墨西超 =====
    'Club America': '墨西哥美洲', 'Club América': '墨西哥美洲',
    'CF Monterrey': '蒙特雷',
    'Tigres UANL': '老虎大学',
    'Cruz Azul': '蓝十字',
    'Guadalajara': '瓜达拉哈拉', 'CD Guadalajara': '瓜达拉哈拉',
    'Pachuca': '帕丘卡', 'CF Pachuca': '帕丘卡',
    'Toluca': '托卢卡', 'Deportivo Toluca': '托卢卡',
    'Santos Laguna': '桑托斯拉古纳',
    'Club Leon': '莱昂', 'Club León': '莱昂',
    'Pumas UNAM': '美洲狮',
    'Atlas FC': '阿特拉斯',
    'Atletico San Luis': '圣路易斯竞技', 'Atlético San Luis': '圣路易斯竞技',
    'Mazatlan FC': '马萨特兰', 'Mazatlán FC': '马萨特兰',
    'Juarez FC': '华雷斯', 'FC Juárez': '华雷斯',
    'Club Tijuana': '蒂华纳',
    'Necaxa': '内卡萨',
    'Queretaro': '克雷塔罗', 'Querétaro FC': '克雷塔罗',
    'Puebla': '普埃布拉',
    'Atlante FC': '亚特兰特',

    # ===== 阿甲 =====
    'River Plate': '河床', 'CA River Plate': '河床',
    'Boca Juniors': '博卡青年',
    'Racing Club': '竞技俱乐部', 'Racing Club de Avellaneda': '竞技俱乐部',
    'Independiente': '独立', 'CA Independiente': '独立',
    'San Lorenzo': '圣洛伦索', 'CA San Lorenzo': '圣洛伦索',
    'Velez Sarsfield': '萨斯菲尔德', 'Vélez Sarsfield': '萨斯菲尔德',
    'Estudiantes La Plata': '拉普拉塔大学生', 'Estudiantes de La Plata': '拉普拉塔大学生',
    'Newells Old Boys': '纽维尔老男孩', "Newell's Old Boys": '纽维尔老男孩',
    'Rosario Central': '罗萨里奥中央',
    'Talleres Cordoba': '科尔多瓦铁路工场', 'Talleres de Córdoba': '科尔多瓦铁路工场',
    'Defensa y Justicia': '国防与司法',
    'Lanus': '拉努斯', 'CA Lanús': '拉努斯',
    'Argentinos Juniors': '阿根廷青年人',
    'Godoy Cruz': '戈多伊克鲁斯',
    'Banfield': '班菲尔德',
    'Huracan': '飓风', 'CA Huracán': '飓风',
    'Platense': '普拉滕斯',
    'Union Santa Fe': '圣菲联合', 'Unión de Santa Fe': '圣菲联合',
    'Sarmiento': '萨米恩托',
    'Barracas Central': '巴拉卡斯中央',
    'Tigre': '蒂格雷',
    'Belgrano': '贝尔格拉诺',
    'Instituto': '科尔多瓦学院', 'Instituto De Córdoba': '科尔多瓦学院',
    'Deportivo Riestra': '列斯特拉体育',
    'Aldosivi': '阿尔多西维',
    'Gimnasia La Plata': '拉普拉塔体操', 'Gimnasia y Esgrima': '拉普拉塔体操',
    'Atletico Tucuman': '图库曼竞技', 'Atlético Tucumán': '图库曼竞技',
    'Central Cordoba SdE': '科尔多瓦中央', 'Central Córdoba': '科尔多瓦中央',
    'Independiente Rivadavia': '里瓦达维亚独立',

    # ===== 哥伦甲 =====
    'Atletico Nacional': '国民竞技', 'Atlético Nacional': '国民竞技',
    'Millonarios': '百万富翁',
    'Independiente Santa Fe': '圣菲独立',
    'Independiente Medellin': '麦德林独立', 'Independiente Medellín': '麦德林独立',
    'Deportivo Cali': '卡利体育',
    'America de Cali': '卡利美洲', 'América de Cali': '卡利美洲',
    'Junior Barranquilla': '巴兰基亚青年', 'Junior FC': '巴兰基亚青年',
    'Once Caldas': '卡尔达斯',
    'Deportes Tolima': '托利马体育',
    'Deportivo Pasto': '帕斯托体育',
    'La Equidad': '公平竞赛',
    'Aguilas Doradas': '金鹰', 'Águilas Doradas': '金鹰',
    'Bucaramanga': '布卡拉曼加', 'Atlético Bucaramanga': '布卡拉曼加',
    'Deportivo Pereira': '佩雷拉体育',
    'Alianza Petrolera': '石油联盟',
    'Envigado': '恩维加多', 'Envigado FC': '恩维加多',
    'Jaguares de Cordoba': '科尔多瓦美洲虎', 'Jaguares de Córdoba': '科尔多瓦美洲虎',
    'Boyaca Chico': '博亚卡奇科', 'Boyacá Chicó FC': '博亚卡奇科',
    'Fortaleza CEIF': '福塔莱萨',

    # ===== 保甲 =====
    'Ludogorets': '卢多戈雷茨', 'Ludogorets Razgrad': '卢多戈雷茨',
    'CSKA Sofia': '索菲亚中央陆军',
    'Levski Sofia': '索菲亚列夫斯基',
    'Lokomotiv Plovdiv': '普罗夫迪夫火车头',
    'Botev Plovdiv': '普罗夫迪夫博特夫',
    'Cherno More': '瓦尔纳黑海', 'Cherno More Varna': '瓦尔纳黑海',
    'Beroe': '贝罗', 'Beroe Stara Zagora': '贝罗',
    'Botev Vratsa': '弗拉察博特夫',
    'Arda Kardzhali': '阿尔达',
    'FC CSKA 1948 Sofia': '索菲亚1948中央陆军',
    'FK Dunav Ruse': '多瑙河鲁塞',
    'Slavia Sofia': '索菲亚斯拉维亚',
    'Spartak Varna': '瓦尔纳斯巴达',
    'Lokomotiv Sofia': '索菲亚火车头',
    'Etar': '埃塔尔',

    # ===== 瑞士超 =====
    'Young Boys': '年轻人', 'BSC Young Boys': '年轻人',
    'FC Basel': '巴塞尔', 'FC Basel 1893': '巴塞尔',
    'FC Zurich': '苏黎世', 'FC Zürich': '苏黎世',
    'FC Lugano': '卢加诺',
    'FC St. Gallen': '圣加仑', 'FC St. Gallen 1879': '圣加仑',
    'Servette': '塞尔维特', 'Servette FC': '塞尔维特',
    'FC Luzern': '卢塞恩',
    'Grasshopper Club Zurich': '苏黎世草蜢', 'Grasshopper Club Zürich': '苏黎世草蜢',
    'FC Sion': '锡永',
    'FC Lausanne-Sport': '洛桑体育',
    'FC Winterthur': '温特图尔',
    'Yverdon Sport': '伊韦尔东', 'Yverdon-Sport FC': '伊韦尔东',
    'FC Vaduz': '瓦杜兹',

    # ===== 英冠 =====
    'Sunderland': '桑德兰', 'Sunderland AFC': '桑德兰',
    'Wrexham': '雷克瑟姆', 'Wrexham AFC': '雷克瑟姆',
    'Barnsley': '巴恩斯利', 'Barnsley FC': '巴恩斯利',
    'Guiseley': '吉斯利', 'Guiseley AFC': '吉斯利',

    # ===== 欧战 =====
    'Sabah FK': '萨巴赫',
    'Kairat Almaty': '凯拉特',
    'FC Iberia 1999': '伊比利亚1999',
    'Larne FC': '拉恩',

    # ===== 友谊赛/其他 =====
    'Udinese': '乌迪内斯', 'Udinese Calcio': '乌迪内斯',
    'Atalanta': '亚特兰大', 'Atalanta BC': '亚特兰大',
    'Sevilla': '塞维利亚', 'Sevilla FC': '塞维利亚',
    'Cagliari': '卡利亚里', 'Cagliari Calcio': '卡利亚里',
    'Torino': '都灵', 'Torino FC': '都灵',
    'AEK Athens': '雅典AEK', 'AEK': '雅典AEK',
    'Sint-Truidense VV': '圣图尔登', 'Sint-Truiden': '圣图尔登',
    'KRC Genk': '亨克', 'Genk': '亨克',
    'Royal Antwerp FC': '安特卫普', 'Antwerp': '安特卫普',
    'Leyton Orient': '莱顿东方',
    'FC Utrecht': '乌德勒支',
    'Parma': '帕尔马', 'Parma Calcio 1913': '帕尔马',
    'FK Suduva': '苏杜瓦', 'FK Sūduva Marijampolė': '苏杜瓦',
    'APS Atromitos Athinon': '阿特罗米托斯',
    'Al-Ain': '艾因', 'Al Diriyah': '迪里耶',
    'FC Hansa Rostock': '罗斯托克', 'Hansa Rostock': '罗斯托克',
    'TSG Neustrelitz': '诺伊斯特雷利茨',
    'Alemannia Aachen': '亚琛',
    'Eintracht Trier': '特里尔',
    '1. FC Union Berlin': '柏林联合',
    'SV Sparta Lichtenberg': '利希滕贝格',
    'VfB 1921 Krieschow': '克里绍',
    'FC Viktoria Koln': '科隆维多利亚', 'FC Viktoria Köln': '科隆维多利亚',
    '1. FC Kaiserslautern II U23': '凯泽斯劳滕二队',
    'KSV Oudenaarde': '奥德纳尔德',
    'FCV Dender': '登德尔',
    'FC Volendam': '福伦丹',
    'Hellas Verona': '维罗纳',
    'Lecco': '莱科',
    'Lanciano FC': '兰恰诺',
    'Pescara': '佩斯卡拉',
    'Ascoli': '阿斯科利',
    'Næstved Boldklub': '奈斯特韦兹',

    # ===== 澳超 =====
    'Melbourne City': '墨尔本城',
    'Central Coast Mariners': '中央海岸水手',
    'Sydney FC': '悉尼FC',
    'Western Sydney Wanderers': '西悉尼漫步者',
    'Adelaide United': '阿德莱德联',
    'Melbourne Victory': '墨尔本胜利',
    'Brisbane Roar': '布里斯班狮吼',
    'Perth Glory': '珀斯光荣',
    'Newcastle Jets': '纽卡斯尔喷气机',
    'Wellington Phoenix': '惠灵顿凤凰',
    'Macarthur FC': '麦克阿瑟FC',
    'Western United': '西部联',

    # ===== MLS =====
    'Inter Miami CF': '迈阿密国际',
    'Columbus Crew': '哥伦布机员',
    'LA Galaxy': '洛杉矶银河',
    'Los Angeles FC': '洛杉矶FC', 'LAFC': '洛杉矶FC',
    'New York City FC': '纽约城', 'NYCFC': '纽约城',
    'New York Red Bulls': '纽约红牛',
    'Atlanta United': '亚特兰大联',
    'Seattle Sounders FC': '西雅图海湾人',
    'Portland Timbers': '波特兰伐木者',
    'FC Dallas': '达拉斯FC',
    'Austin FC': '奥斯汀FC',
    'Minnesota United': '明尼苏达联',
    'Chicago Fire': '芝加哥火焰',
    'Charlotte FC': '夏洛特FC',
    'Sporting Kansas City': '堪萨斯城体育',
    'Houston Dynamo': '休斯敦迪纳摩',
    'St.Louis City': '圣路易斯城', 'St. Louis City SC': '圣路易斯城',
    'Real Salt Lake': '皇家盐湖城',
    'Colorado Rapids': '科罗拉多急流',
    'San Diego FC': '圣迭戈FC',
    'Nashville SC': '纳什维尔',

    # ===== 美冠 (USL) =====
    'FC Tampa Bay Rowdies': '坦帕湾暴徒',
    'Louisville City FC': '路易斯维尔城',
    'Birmingham Legion FC': '伯明翰军团',
    'Rhode Island FC': '罗德岛',
    'New Mexico United': '新墨西哥联',
    'Colorado Springs Switchbacks FC': '科罗拉多斯普林斯',
    'Orange County SC': '奥兰治县',
    'El Paso Locomotive FC': '埃尔帕索火车头',
    'Oakland Roots SC': '奥克兰根',
    'Pittsburgh Riverhounds': '匹兹堡河犬',
    'Las Vegas Lights': '拉斯维加斯灯光',
    'Phoenix Rising FC': '菲尼克斯崛起',
    'Sacramento Republic FC': '萨克拉门托共和',
    'SC Jacksonville': '杰克逊维尔',

    # ===== 澳NPL =====
    'Magic United TFA': '魔术联',
    'Olympic FC': '奥林匹克FC',
    'Brisbane Roar Youth': '布里斯班狮吼青年',
    'Moreton City Excelsior FC': '摩顿城',

    # ===== 巴甲 =====
    'Palmeiras': '帕尔梅拉斯', 'SE Palmeiras': '帕尔梅拉斯',
    'Flamengo': '弗拉门戈', 'CR Flamengo': '弗拉门戈',
    'Santos': '桑托斯', 'Santos FC': '桑托斯',
    'Corinthians': '科林蒂安', 'SC Corinthians': '科林蒂安',
    'Sao Paulo': '圣保罗', 'São Paulo FC': '圣保罗',
    'Gremio': '格雷米奥', 'Grêmio': '格雷米奥',
    'Internacional': '巴西国际', 'SC Internacional': '巴西国际',
    'Atletico Mineiro': '米内罗竞技', 'Atlético Mineiro': '米内罗竞技',
    'Fluminense': '弗鲁米嫩塞', 'Fluminense FC': '弗鲁米嫩塞',
    'Botafogo': '博塔弗戈', 'Botafogo FR': '博塔弗戈',
    'Fortaleza': '福塔莱萨', 'Fortaleza EC': '福塔莱萨',
    'Cruzeiro': '克鲁塞罗', 'Cruzeiro EC': '克鲁塞罗',
    'Chapecoense': '沙佩科恩斯', 'Chapecoense AF': '沙佩科恩斯',
    'Mirassol': '米拉索尔', 'Mirassol FC': '米拉索尔',
    'Remo': '雷莫', 'Clube do Remo': '雷莫',
    'Bragantino': '布拉干蒂诺', 'Red Bull Bragantino': '布拉干蒂诺',
    'Athletico Paranaense': '巴拉纳竞技', 'Athletico-PR': '巴拉纳竞技',
    'Bahia': '巴伊亚', 'EC Bahia': '巴伊亚',
    'Vasco da Gama': '瓦斯科达伽马', 'CR Vasco da Gama': '瓦斯科达伽马',
    'Cuiaba': '库亚巴', 'Cuiabá EC': '库亚巴',
    'Coritiba': '科里蒂巴', 'Coritiba FC': '科里蒂巴',
    'Goias': '戈亚斯', 'Goiás EC': '戈亚斯',
    'America Mineiro': '米内罗美洲', 'América Mineiro': '米内罗美洲',
    'Ceara': '塞阿拉', 'Ceará SC': '塞阿拉',
    'Sport Recife': '累西腓体育',
    'Avai': '阿瓦伊', 'Avaí FC': '阿瓦伊',
    'Juventude': '尤文图德', 'EC Juventude': '尤文图德',
    'Atletico Goianiense': '戈亚尼亚竞技', 'Atlético Goianiense': '戈亚尼亚竞技',
    'Vitoria': '维多利亚', 'EC Vitória': '维多利亚',
    'CRB': '巴西雷加塔斯', 'CRB AL': '巴西雷加塔斯',
    'Criciuma': '克里西乌马', 'Criciúma EC': '克里西乌马',

    # ===== 阿根廷杯赛 =====
    'CA Lanús': '拉努斯', 'Lanus': '拉努斯',
    'Instituto De Córdoba': '科尔多瓦学院', 'Instituto': '科尔多瓦学院',
    'CA Independiente': '独立',
    'CA River Plate': '河床',
    'CA San Lorenzo': '圣洛伦索',
    'Vélez Sarsfield': '萨斯菲尔德',
    'Gimnasia y Esgrima': '拉普拉塔体操',
    'Rosario Central': '罗萨里奥中央',
    'Aldosivi': '阿尔多西维',

    # ===== 德国/欧洲其他 =====
    'FK Sūduva Marijampolė': '苏杜瓦', 'FK Suduva': '苏杜瓦',
    'FC Dender': '登德尔', 'FCV Dender EH': '登德尔',
    'FC Twente': '特温特',
    'FC Volendam': '福伦丹',
    'Hellas Verona': '维罗纳',
    'Ascoli Calcio 1898 FC': '阿斯科利',
    'Næstved Boldklub': '奈斯特韦兹', 'Naestved': '奈斯特韦兹',
    'GKS Katowice': '卡托维兹',
    'Radomiak Radom': '拉多米亚克',
    'CSKA Sofia': '索菲亚中央陆军',
    'FK Dunav Ruse': '多瑙河鲁塞',
    'Kairat Almaty': '凯拉特',
    'Sabah FK': '萨巴赫',
    'FC Iberia 1999': '伊比利亚1999',
    'Larne FC': '拉恩',
    'Levski Sofia': '索菲亚列夫斯基',
    'Botev Vratsa': '弗拉察博特夫',
    'Arda Kardzhali': '阿尔达',
    'FC CSKA 1948 Sofia': '索菲亚1948中央陆军',
    'Trabzonspor': '特拉布宗体育',
    'Galatasaray SK': '加拉塔萨雷',
    'Stade Rennais FC': '雷恩',
    'Birmingham Legion FC': '伯明翰军团',
    'Rhode Island FC': '罗德岛',
    'Denver Summit FC': '丹佛巅峰',
    'Boston Legacy FC': '波士顿遗产',
    'FC Corvinul Hunedoara': '科尔维努尔',
    'Sepsi OSK Sfântu Gheorghe': '舍佩斯',
    'FC Rapid București': '布加勒斯特快速',
    'CFR 1907 Cluj': '克卢日',
    'Silkeborg IF': '锡尔克堡',
    'AC Horsens': '霍森斯',
    'Viborg FF': '维堡',
    'Randers FC': '兰讷斯',
    'Brøndby IF': '布隆德比',
    'FC Midtjylland': '中日德兰',
    'FC Nordsjælland': '北西兰',
    'FC København': '哥本哈根',
    'Degerfors IF': '代格福什',
    'IF Brommapojkarna': '布鲁马波卡纳',
    'AIK': '索尔纳AIK',
    'Örgryte IS': '厄尔格里特',
    'IFK Göteborg': '哥德堡',
    'Malmö FF': '马尔默',
    'Śląsk Wrocław': '弗罗茨瓦夫',
    'Legia Warszawa': '华沙军团',
    'Raków Częstochowa': '琴斯托霍瓦',
    'Zagłębie Lubin': '卢宾扎格列比',
    'VPS': '瓦萨',
    'Inter Turku': '图尔库国际',
    'AC Oulu': '奥卢',
    'Ilves': '伊尔韦斯',
    'Molde FK': '莫尔德',
    'Sarpsborg 08': '萨普斯堡',
    'Kristiansund BK': '克里斯蒂安松',
    'KFUM Oslo': 'KFUM奥斯陆',
    'SK Brann': '布兰',
    'Rosenborg BK': '罗森博格',
    'Tromsø IL': '特罗姆瑟',
    'Aalesunds FK': '奥勒松',
    'Daejeon Hana Citizen': '大田市民',
    'Gwangju FC': '光州FC',
    'FC Anyang': '安养FC',
    'Jeju SK': '济州联',
    'Incheon United': '仁川联',
    'Ulsan HD FC': '蔚山现代',
    'Cruz Azul': '蓝十字',
    'CF Pachuca': '帕丘卡',
    'Club León': '莱昂',
    'Santos Laguna': '桑托斯拉古纳',
    'Atlas FC': '阿特拉斯',
    'CF Monterrey': '蒙特雷',
    'Club América': '墨西哥美洲',
    'Atlante FC': '亚特兰特',
    'Liga Deportiva Alajuelense': '阿拉胡埃伦斯',
    'CS Herediano': '埃雷迪亚诺',
    'Categoría Primera A': '哥伦甲',
    'Atlético Nacional': '国民竞技',
    'Millonarios': '百万富翁',
    'Independiente Santa Fe': '圣菲独立',
    'Once Caldas': '卡尔达斯',
    'Jaguares de Córdoba': '科尔多瓦美洲虎',
    'América de Cali': '卡利美洲',
    'Boyacá Chicó FC': '博亚卡奇科',
    'Junior Barranquilla': '巴兰基亚青年',
    'Junior FC': '巴兰基亚青年',
    'NWSL': None,

    # ===== 欧战/各国杯赛 补充 =====
    'Bodø/Glimt': '博德闪耀', 'Bod?/Glimt': '博德闪耀', 'Bodo/Glimt': '博德闪耀',
    'FK Bodø/Glimt': '博德闪耀',
    'FK Crvena Zvezda': '贝尔格莱德红星', 'Crvena Zvezda': '贝尔格莱德红星',
    'Olympiacos FC': '奥林匹亚科斯', 'Olympiacos': '奥林匹亚科斯',
    'Panathinaikos FC': '帕纳辛纳科斯', 'Panathinaikos': '帕纳辛纳科斯',
    'GNK Dinamo Zagreb': '萨格勒布迪纳摩', 'Dinamo Zagreb': '萨格勒布迪纳摩',
    'FK Kauno Žalgiris': '考纳斯扎尔吉里斯', 'FK Kauno ?algiris': '考纳斯扎尔吉里斯',
    'Hapoel Beer Sheva': '贝尔谢巴夏普尔', "Hapoel Be'er Sheva": '贝尔谢巴夏普尔',
    'Apollon Limassol': '利马索尔阿波罗',
    'Royale Union Saint-Gilloise': '圣吉罗斯联合', 'Union Saint-Gilloise': '圣吉罗斯联合',
    'ŠK Slovan Bratislava': '布拉迪斯拉发斯拉夫人', '?K Slovan Bratislava': '布拉迪斯拉发斯拉夫人', 'Slovan Bratislava': '布拉迪斯拉发斯拉夫人',
    'Mjällby AIF': '米亚尔比', 'Mj?llby AIF': '米亚尔比',
    'Fenerbahçe': '费内巴切', 'Fenerbahce': '费内巴切',
    'Beşiktaş': '贝西克塔斯', 'Besiktas': '贝西克塔斯',
    'AEK': '雅典AEK', 'AEK Athens': '雅典AEK',
    'NEC Nijmegen': '奈梅亨', 'NEC': '奈梅亨',
    'POT Iraklis': '伊拉克利斯',
    'KSV Oudenaarde': '奥德纳尔德',
    'FCV Dender': '登德尔',
    'FC Viktoria Köln': '科隆维多利亚',
    'FK Sūduva': '苏杜瓦', 'FK Sūduva Marijampolė': '苏杜瓦',
    '1. FC Kaiserslautern II U23': '凯泽斯劳滕二队',
    'SV Sparta Lichtenberg': '利希滕贝格',
    'VfB 1921 Krieschow': '克里绍',
    'TSG Neustrelitz': '诺伊斯特雷利茨',
    'Alemannia Aachen': '亚琛',
    'Eintracht Trier': '特里尔',
    'Guiseley AFC': '吉斯利', 'Guiseley': '吉斯利',
    'Al-Ain Al Diriyah': '艾因迪里耶', 'Al-Ain': '艾因',
    'FC Hansa Rostock': '罗斯托克',
    'AE Kifisia': '基菲夏',
    'RKC Waalwijk': '瓦尔韦克',
    'Sint-Truidense VV': '圣图尔登', 'Sint-Truiden': '圣图尔登',
    'KRC Genk': '亨克',
    'ASC Oțelul Galați': '加拉茨钢铁',
    'APS Atromitos Athinon': '阿特罗米托斯',
    'Dinamo București': '布加勒斯特迪纳摩',
    'FC Rapid București': '布加勒斯特快速',
    'Sepsi OSK Sfântu Gheorghe': '舍佩斯',
    'FC Corvinul Hunedoara': '科尔维努尔',
    'Aalesunds FK': '奥勒松',
    'Kristiansund BK': '克里斯蒂安松',
    'KFUM-Kameratene Oslo': 'KFUM奥斯陆',
    'Sandefjord Fotball': '桑纳菲尤尔',
    'FK Haugesund': '海于格松',
    'Odds BK': '奥德',
    'Lillestrøm SK': '利勒斯特罗姆',
    'Strømsgodset IF': '斯特罗姆加斯特',
    'Fredrikstad FK': '腓特烈斯塔',
    'Bryne FK': '布莱尼',
    'ACK AC Oulu': '奥卢',
    'Seinäjoen Jalkapallokerho': '塞伊奈约基',
    'Vaasan Palloseura': '瓦萨',
    'Kuopion Palloseura': '库普斯',
    'BSC Young Boys': '年轻人',
    'FC Basel 1893': '巴塞尔',
    'FC Zürich': '苏黎世',
    'Servette FC': '塞尔维特',
    'Grasshopper Club Zürich': '苏黎世草蜢',
    'FC Lausanne-Sport': '洛桑体育',
    'FC Winterthur': '温特图尔',
    'Yverdon-Sport FC': '伊韦尔东',
    'FC Vaduz': '瓦杜兹',
    'FC Wil 1900': '韦尔',
    'Étoile Carouge FC': '卡鲁日之星',
    'FC Schaffhausen': '沙夫豪森',
    'FC Aarau': '阿劳',
    'Neuchâtel Xamax': '纳沙泰尔',
    'FC Stade Nyonnais': '尼永',
    'FC Stade Lausanne Ouchy': '洛桑乌契',
    'FC Thun': '图恩',
    # ===== 东欧/北欧 补充 =====
    'NK Celje': '采列', 'NK Celje FC': '采列',
    'FC Ararat-Armenia': '亚美尼亚亚拉腊', 'Ararat-Armenia': '亚美尼亚亚拉腊',
    'SK Sturm Graz': '格拉茨风暴', 'Sturm Graz': '格拉茨风暴',
    'CA Talleres': '科尔多瓦铁路工场', 'Talleres': '科尔多瓦铁路工场', 'Talleres Cordoba': '科尔多瓦铁路工场',
    'Debreceni VSC': '德布勒森', 'Debrecen': '德布勒森',
    'AC Sparta Praha': '布拉格斯巴达', 'Sparta Praha': '布拉格斯巴达', 'Sparta Prague': '布拉格斯巴达',
    'SK Rapid Wien': '维也纳快速', 'Rapid Wien': '维也纳快速', 'Rapid Vienna': '维也纳快速',
    'FK Partizan': '贝尔格莱德游击', 'Partizan Belgrade': '贝尔格莱德游击',
    'Ferencvaros': '费伦茨瓦罗斯', 'Ferencvárosi TC': '费伦茨瓦罗斯',
    'Slavia Praha': '布拉格斯拉维亚', 'Slavia Prague': '布拉格斯拉维亚',
    'Viktoria Plzen': '比尔森胜利', 'FC Viktoria Plzeň': '比尔森胜利',
    'Lech Poznań': '波兹南莱赫', 'Lech Poznan': '波兹南莱赫',
    'Legia Warsaw': '华沙军团',
    'Raków Częstochowa': '琴斯托霍瓦',
    'Pogoń Szczecin': '什切青波贡',
    'Jagiellonia Białystok': '比亚韦斯托克',
    'Zagłębie Lubin': '卢宾扎格列比',
    'Śląsk Wrocław': '弗罗茨瓦夫',
    'Widzew Łódź': '罗兹维德泽夫',
    'Górnik Zabrze': '扎布热矿工',
    'Piast Gliwice': '皮亚斯特',
    'Puszcza Niepołomice': '涅波沃米采',
    'Stal Mielec': '梅莱茨钢铁',
    'Korona Kielce': '凯尔采王冠',
    'Motor Lublin': '卢布林摩托',
    'Cracovia': '克拉科维亚',
    'MŠK Žilina': '日利纳', 'MSK Zilina': '日利纳',
    'FC DAC 1904 Dunajská Streda': '多瑙斯特雷达',
    'Spartak Trnava': '特尔纳瓦斯巴达',
    'FK Železiarne Podbrezová': '波德布雷佐瓦',
    'MFK Ružomberok': '鲁容贝罗克',
    'AS Trenčín': '特伦钦',
    'FK Dukla Banská Bystrica': '班斯卡比斯特里察',
    'MFK Skalica': '斯卡利察',
    'MFK Zemplín Michalovce': '米哈洛夫采',
    'FC Košice': '科希策',
    'FC ViOn Zlaté Moravce': '兹拉特莫拉夫采',
    'NK Maribor': '马里博尔',
    'NK Olimpija Ljubljana': '卢布尔雅那奥林匹亚',
    'FC Koper': '科佩尔',
    'NK Bravo': '布拉沃',
    'ND Gorica': '戈里察',
    'FC Lugano': '卢加诺',
    'FC St. Gallen 1879': '圣加仑',
    'FC Luzern': '卢塞恩',
    'FC Sion': '锡永',
}

